config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  root "static_pages#top"
  get "/privacypolicy", to: "static_pages#privacypolicy"
  get "/terms", to: "static_pages#terms"
  get "/login", to: "user_sessions#new"
  post "/login", to: "user_sessions#create"
  delete "/logout", to: "user_sessions#destroy"
  
  get 'auth/:provider/callback', to: "user_sessions#create"
  get 'auth/failure', to: redirect('/')

  resources :users do
    member do
      get :edit_best, :channels, :videos, :playlists, :contents, :following, :follower
    end
  end

  # 本番環境でメールサーバーの契約予定がないため削除
  # resources :password_resets, only: %i[new create edit update]
  
  resources :relationships, only: %i[create destroy]
  resources :channels, only: %i[index], shallow: true do
    resources :channel_comments, only: %i[new create edit update destroy]
    member do
      get :users, :videos, :comments, :playlists
    end
  end
  resources :videos, only: %i[index show], shallow: true do
    resources :video_comments, only: %i[new create edit update destroy]
  end
  resources :contents, shallow: true do
    resources :content_comments, only: %i[new create edit update destroy]
  end
  resources :content_favorites, only: %i[create destroy]
  resources :best_channels_favorites, only: %i[create destroy]
  resources :best_videos_favorites, only: %i[create destroy]
  resource :best_videos, only: %i[edit update]
  resource :best_channels, only: %i[edit update]
  resource :subscription_channels, only: %i[edit update]
  resource :popular_videos, only: %i[edit update]
  resource :recent_content, only: %i[show]
  resource :user_playlists, only: %i[edit update]
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  belongs_to :video
  has_many :content_comments, dependent: :destroy
  has_many :content_favorites, dependent: :destroy

  validates :video_url, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, in: 1..5 }
  validates :feedback, presence: true, length: { maximum: 400 }
  validate :video_url_is_youtube_url

  default_scope -> { order(created_at: :desc) }

  private

  def video_url_is_youtube_url
    return unless video_url.present?

    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = Settings.google_api_key

    video = service.list_videos(:snippet, id: video_url).items.first
    errors.add(:video_url, 'は不正なURLです。') if video.blank?
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  skip_before_action :require_login, only: %i[index show]
  before_action :set_content, only: %i[edit update destroy]

  def index
    @contents = Content.includes(:user, video: :channel).order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    @content = Content.find(params[:id])
    @content_comments = @content.content_comments.includes(:user).page(params[:page])
  end

  def new
    @content_form = ContentsForm.new(current_user)
    @content_form.video_url = params[:video_url]
  end

  def create
    @content_form = ContentsForm.new(current_user, contents_form_params)

    if @content_form.save(contents_form_params)
      redirect_to contents_url, success: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @content_form = ContentsForm.new(current_user, {}, @content)
  end

  def update
    @content_form = ContentsForm.new(current_user, contents_form_params, @content)
    if @content_form.update(contents_form_params)
      redirect_to @content, success: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @content.destroy!
    respond_to do |format|
      format.html { redirect_to contents_url, success: t('.success'), status: :see_other }
      format.turbo_stream { flash.now[:success] = t('.success') }
    end
  end

  private

  def contents_form_params
    params.require(:contents_form).permit(:video_url, :rating, :feedback)
  end

  def set_content
    @content = current_user.contents.find(params[:id])
  end
end

app/views/contents/_content.html.erb
<div id="content-<%= content.id %>" class="row user-content">
  <div class="col-md-6 text-center">
    <iframe width="336" height="189" src=<%= content.decorate.youtube_url(content.video_url) %> title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  </div>
  <div class="col-md-6 post-contents">
    <%= link_to content do %>
      <p>動画タイトル:<%= content.video.title %></p>
    <% end %>
    <p>チャンネル名：<%= content.video.channel.name %></p>
    <p>評価：<%= content.decorate.rating(content.rating) %></p>
    <p id="content-feedback-<%= content.id %>">感想：<%= content.feedback %></p>
    <%= link_to channels_user_path(content.user) do %>
      <span id="user-name-<%= content.user.id %>" class="user-name"><%= "投稿者：#{content.user.name}" %></span>
    <% end %>
  </div>
  <%= render 'content_favorites/favorite_btn', content: content if logged_in? %>
  <% if current_user?(content.user) %>
    <%= link_to "編集", edit_content_path(content), class: "btn btn-primary" %>
    <%= link_to "削除", content, data: { "turbo-method": :delete, turbo_confirm: "投稿を削除してよろしいですか?" }, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/contents/_favorite_btn.html.erb
<span id="favorite-btn-<%= content.id %>" class="favorite-btn">
<% if current_user.like_content?(content) %>
  <%= render 'content_favorites/unlike', content: content %>
<% else %>
  <%= render 'content_favorites/like', content: content %>
<% end %>
</span>

app/views/contents/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @content_form, url: url, method: method, class: "new-contents-form" do |f| %>
      <h1 class="text-center"><%= "投稿の#{title}" %></h1>

      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :video_url, class: "form-label" %>
        <%= f.text_field :video_url, class: "form-control", placeholder: "視聴した動画のURLを記載してください" %>
      </div>

      <div class="form-group">
        <%= f.label :rating, class: "form-label" %>
        <%= f.select :rating, (1..5).to_a, { include_blank: "1〜5を選択してください" }, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :feedback, class: "form-label" %>
        <%= f.text_area :feedback, size: "40x10", class: "form-control", placeholder: "動画の感想を入力してください" %>
      </div>

      <%= f.submit "投稿する", class: "btn btn-primary btn-block mt-30" %>
    <% end %>
  </div>
</div>

app/views/contents/_user_contents.html.erb
<% if @contents.size > 0 %>
  <span class="text-center"><%= paginate @contents, theme: 'bootstrap-5' %></span>
  <%= render @contents %>
  <span class="text-center"><%= paginate @contents, theme: 'bootstrap-5' %></span>
<% else %>
  <p class="not-found">投稿はありません</p>
<% end %>

app/views/contents/destroy.turbo_stream.erb
<%= turbo_stream.remove "content-#{@content.id}" %>

<%= turbo_stream.update "flash-message" do %>
  <%= render 'shared/flash_message' %>
<% end %>

app/views/contents/edit.html.erb
<% content_for(:title, t(".title")) %>

<%= render 'form', url: content_path(@content), title: "編集", method: "patch" %>

app/views/contents/index.html.erb
<% content_for(:title, t(".title")) %>
<h1 class="text-center"><%= t(".title") %></h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <span class="text-center"><%= paginate @contents, theme: 'bootstrap-5' %></span>
    <%= render @contents %>
    <span class="text-center"><%= paginate @contents, theme: 'bootstrap-5' %></span>
  </div>
</div>

app/views/contents/new.html.erb
<% content_for(:title, t(".title")) %>

<%= render 'form', url: contents_path, title: "作成", method: "post" %>

app/views/contents/show.html.erb
<% content_for(:title, t(".title")) %>
<h1 class="text-center"><%= t(".title") %></h1>

<div class="row content-show">
  <div class="col-md-6 text-center">
    <iframe width="336" height="189" src=<%= @content.decorate.youtube_url(@content.video_url) %> title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  </div>
  <div class="col-md-6 post-contents">
    <%= link_to @content do %>
      <p>動画タイトル:節約のメリット10選</p>
    <% end %>
    <p>チャンネル名：倹者の流儀</p>
    <p>評価：<%= @content.decorate.rating(@content.rating) %></p>
    <p id="content-feedback-<%= @content.id %>">感想：<%= @content.feedback %></p>
  </div>

  <div class="col-md-10 col-md-offset-1">
    <div class="mt-30">
      <%= link_to "コメントの新規作成", new_content_content_comment_path(@content), class: "btn btn-primary btn-block" if logged_in? %>
    </div>
    <h2 class="text-center">コメント一覧</h2>
    <div class="text-center"><%= paginate @content_comments, theme: 'bootstrap-5' %></div>
    <%= render @content_comments %>
    <div class="text-center"><%= paginate @content_comments, theme: 'bootstrap-5' %></div>
  </div>
</div>