config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  root "static_pages#top"
  get "/privacypolicy", to: "static_pages#privacypolicy"
  get "/terms", to: "static_pages#terms"
  get "/login", to: "user_sessions#new"
  post "/login", to: "user_sessions#create"
  delete "/logout", to: "user_sessions#destroy"
  
  get 'auth/:provider/callback', to: "user_sessions#create"
  get 'auth/failure', to: redirect('/')

  resources :users do
    member do
      get :edit_best, :channels, :videos, :playlists, :contents, :following, :follower
    end
  end

  # 本番環境でメールサーバーの契約予定がないため削除
  # resources :password_resets, only: %i[new create edit update]
  
  resources :relationships, only: %i[create destroy]
  resources :channels, only: %i[index], shallow: true do
    resources :channel_comments, only: %i[new create edit update destroy]
    member do
      get :users, :videos, :comments, :playlists
    end
  end
  resources :videos, only: %i[index show], shallow: true do
    resources :video_comments, only: %i[new create edit update destroy]
  end
  resources :contents, shallow: true do
    resources :content_comments, only: %i[new create edit update destroy]
  end
  resources :content_favorites, only: %i[create destroy]
  resources :best_channels_favorites, only: %i[create destroy]
  resources :best_videos_favorites, only: %i[create destroy]
  resource :best_videos, only: %i[edit update]
  resource :best_channels, only: %i[edit update]
  resource :subscription_channels, only: %i[edit update]
  resource :popular_videos, only: %i[edit update]
  resource :recent_content, only: %i[show]
  resource :user_playlists, only: %i[edit update]
end

app/models/user.rb
class User < ApplicationRecord
  GOOGLE_API_SERVICE = Google::Apis::YoutubeV3::YouTubeService.new

  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader

  before_save :downcase_email

  has_many :contents, dependent: :destroy
  has_many :active_relationships,  class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :subscription_channels, dependent: :destroy
  has_many :channels, through: :subscription_channels, source: :channel
  has_many :popular_videos, dependent: :destroy
  has_many :videos, through: :popular_videos, source: :video
  has_many :best_videos, dependent: :destroy
  has_many :favorite_videos, through: :best_videos, source: :video
  has_many :best_channels, dependent: :destroy
  has_many :favorite_channels, through: :best_channels, source: :channel
  has_many :channel_comments, dependent: :destroy
  has_many :video_comments, dependent: :destroy
  has_many :content_comments, dependent: :destroy
  has_many :content_favorites, dependent: :destroy
  has_many :like_contents, through: :content_favorites, source: :content
  has_many :best_channels_favorites, dependent: :destroy
  has_many :like_best_channels, through: :best_channels_favorites, source: :best_channel
  has_many :best_videos_favorites, dependent: :destroy
  has_many :like_best_videos, through: :best_videos_favorites, source: :best_video
  has_many :user_categories, dependent: :destroy
  has_many :categories, through: :user_categories, source: :category
  has_many :user_playlists, dependent: :destroy

  validates :password, presence: true, length: { minimum: 8, maximum: 16 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :age, allow_nil: true, numericality: { only_integer: true, in: 13..100 }
  validates :gender, presence: true
  validates :profile, length: { maximum: 400 }
  validates :role, presence: true
  validates :reset_password_token, uniqueness: true, allow_nil: true
  validates :remember_me_token, uniqueness: true, allow_nil: true

  # 性別 { 回答なし: 0, 男性: 1, 女性: 2, その他: 9 }
  enum gender: { not_known: 0, male: 1, female: 2, not_applicabel: 9 }
  # 権限 { 一般 : 0, 管理者 : 1 }
  enum role: { general: 0, admin: 1 }

  scope :by_users_generation, ->(users_generation) { where('age BETWEEN ? AND ?', users_generation, users_generation + 9) }
  scope :by_category, ->(category_id) { joins(:user_categories).merge(where(user_categories: { category_id: })) }
  scope :by_channel, ->(channel_id) { joins(:subscription_channels).merge(where(subscription_channels: { channel_id: })) }
  scope :name_contain, ->(name) { where('LOWER(name) LIKE ?', "%#{name}%") }

  def subscription_channels_with_public
    subscription_channels_channel_ids = subscription_channels.where(is_public: true).map(&:channel_id)
    channels.where(id: subscription_channels_channel_ids)
  end

  def popular_videos_with_public
    popular_videos_video_ids = popular_videos.where(is_public: true).map(&:video_id)
    videos.where(id: popular_videos_video_ids)
  end

  def follow(other_user)
    following << other_user unless self == other_user && following?(other_user)
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def like_content(content)
    like_contents << content unless like_content?(content)
  end

  def dislike_content(content)
    like_contents.delete(content)
  end

  def like_content?(content)
    like_contents.include?(content)
  end

  def like_best_channel(best_channel)
    like_best_channels << best_channel unless like_best_channel?(best_channel)
  end

  def dislike_best_channel(best_channel)
    like_best_channels.delete(best_channel)
  end

  def like_best_channel?(best_channel)
    like_best_channels.include?(best_channel)
  end

  def like_best_video(best_video)
    like_best_videos << best_video unless like_best_video?(best_video)
  end

  def dislike_best_video(best_video)
    like_best_videos.delete(best_video)
  end

  def like_best_video?(best_video)
    like_best_videos.include?(best_video)
  end

  def add_or_delete_channels(channel_list)
    old_channels = channels - channel_list
    new_channels = channel_list - channels

    old_channels.each { |channel| channels.delete(channel) }
    new_channels.each { |channel| channels << channel }
  end

  def add_or_delete_videos(video_list)
    old_videos = videos - video_list
    new_videos = video_list - videos

    old_videos.each { |video| videos.delete(video) }
    new_videos.each { |video| videos << video }
  end

  def update_favorite_channels(channels)
    return false unless channels.count == 3

    if favorite_channels.present?
      best_channels.each do |best_channel|
        best_channel.best_channels_favorites.delete_all
        best_channel.delete
      end
    end
    channels.each_with_index do |channel, index|
      best_channels.create(channel:, rank: index + 1)
    end
  end

  def update_favorite_videos(videos)
    return false unless videos.count == 3

    if favorite_videos.present?
      best_videos.each do |best_video|
        best_video.best_videos_favorites.delete_all
        best_video.delete
      end
    end
    videos.each_with_index do |video, index|
      best_videos.create(video:, rank: index + 1)
    end
  end

  def create_playlist(access_token)
    GOOGLE_API_SERVICE.authorization = Signet::OAuth2::Client.new(access_token:)
    playlists = GOOGLE_API_SERVICE.list_playlists(:snippet, mine: true, max_results: 10)
    return if playlists.items.empty?

    playlists.items.each do |playlist_item|
      playlist_params = playlist_params_by_playlist_item(playlist_item)
      playlist_id = playlist_params[:playlist_id]
      playlist = user_playlists.find_or_initialize_by(playlist_id:)
      playlist.update!(playlist_params)
      videos = Video.find_or_create_videos_by_playlist_id(playlist_id)
      UserPlaylistVideo.update_playlist(playlist, videos)
    end
  end

  private

  def downcase_email
    email.downcase!
  end

  def playlist_params_by_playlist_item(playlist_item)
    {
      playlist_id: playlist_item.id,
      title: playlist_item.snippet.title,
      description: playlist_item.snippet.description
    }
  end
end

app/models/video.rb
class Video < ApplicationRecord
  GOOGLE_API_SERVICE = Google::Apis::YoutubeV3::YouTubeService.new

  belongs_to :channel
  belongs_to :category

  has_many :popular_videos, dependent: :destroy
  has_many :users, through: :popular_videos, source: :user
  has_many :video_comments, dependent: :destroy
  has_many :user_playlist_videos, dependent: :destroy

  validates :video_id, presence: true, uniqueness: true
  validates :title, presence: true

  scope :with_users, -> { joins(:popular_videos).where(popular_videos: { video_id: ids }) }
  scope :with_following_users, ->(following_user_ids) { joins(:popular_videos).where(popular_videos: { user_id: following_user_ids }) }
  scope :recent_and_with_users, -> { where('videos.created_at >= ?', 3.days.ago.beginning_of_day).joins(:users).group('videos.id').having('COUNT(users.id) > 0') }
  scope :by_category, ->(category_id) { where(category_id:) }
  scope :by_users_generation, ->(users_generation) { joins(:users).where('age BETWEEN ? AND ?', users_generation, users_generation + 9) }
  scope :channel_name_contain, ->(word) { joins(:channel).where('LOWER(channels.name) LIKE ?', "%#{word}%") }
  scope :description_contain, ->(word) { where('LOWER(description) LIKE ?', "%#{word}%") }

  scope :user_count_order, -> { joins(:users).select('videos.*, COUNT(users.id) as user_count').group('videos.id').order('user_count DESC, created_at DESC') }

  def users_with_public
    popular_videos_user_ids = popular_videos.where(is_public: true).map(&:user_id)
    users.where(id: popular_videos_user_ids)
  end

  class << self
    def create_popular_video_list(access_token)
      video_list = []
      GOOGLE_API_SERVICE.authorization = Signet::OAuth2::Client.new(access_token:)
      videos = GOOGLE_API_SERVICE.list_videos(:snippet, my_rating: 'like', max_results: 30)
      videos.items.each do |video|
        video_list << find_or_create_video_by_video(video)
      end
      video_list
    end

    def find_or_create_videos_by_playlist_id(playlist_id)
      videos = []
      GOOGLE_API_SERVICE.key = Settings.google_api_key
      playlist_videos = GOOGLE_API_SERVICE.list_playlist_items(:snippet, playlist_id:, max_results: 5)
      playlist_videos.items.each do |playlist_video|
        video_id = playlist_video.snippet.resource_id.video_id
        video = find_or_create_video_by_video_id(video_id)
        videos << video if video
      end
      videos
    end

    def find_or_create_video_by_video_id(video_id)
      GOOGLE_API_SERVICE.key = Settings.google_api_key
      video = GOOGLE_API_SERVICE.list_videos(:snippet, id: video_id, max_results: 1).items.first

      return nil unless video.present?

      find_or_create_video_by_video(video)
    end

    def find_or_create_video_by_video(video)
      video_params = video_params_by_video(video)
      video = find_or_initialize_by(video_id: video_params[:video_id])
      video.update(video_params)
      video
    end

    private

    def video_params_by_video(video)
      channel = Channel.find_or_create_channel_by_channel_id(video.snippet.channel_id)
      category_id = video.snippet.category_id || 99
      {
        video_id: video.id,
        title: video.snippet.title,
        description: video.snippet.description,
        channel_id: channel.id,
        category_id: Category.find_by(title: category_id).id
      }
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :require_login

  def index
    @search_videos_form = SearchVideosForm.new(search_params)
    @videos = @search_videos_form.search.user_count_order.page(params[:page]).per(8)
  end

  def show
    @link = params[:link] ||= 'comment'
    @video = Video.find(params[:id])
    @video_comments = @video.video_comments.includes(:user).page(params[:page]) if @link == 'comment'
    @video_users = @video.users_with_public.page(params[:page]) if @link == 'user'
  end

  private

  def search_params
    params[:q]&.permit(:channel_name, :description, :category_title, :users_generation, :following_user_ids, :follow_users)
  end
end

app/views/videos/_channel_videos.html.erb
<div id="channel-videos">
  <span class="text-center"><%= paginate @channel_videos, theme: 'bootstrap-5' %></span>
  <%= render @channel_videos %>
  <span class="text-center"><%= paginate @channel_videos, theme: 'bootstrap-5' %></span>
</div>

app/views/videos/_user_videos.html.erb
<% if @videos.size > 0 %>
  <span class="text-center"><%= paginate @videos, theme: 'bootstrap-5' %></span>
  <%= render @videos %>
  <span class="text-center"><%= paginate @videos, theme: 'bootstrap-5' %></span>
<% else %>
  <p class="not-found">公開中の高評価動画はありません</p>
<% end %>

app/views/videos/_video.html.erb
<% video_users = video.users_with_public.take(5) %>

<div class="video">
  <div class="text-center">
    <iframe width="336" height="189" src=<%= "https://www.youtube.com/embed/#{video.video_id}" %> title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  </div>
  <div class="video-info">
    <%= link_to video do %>
      <p id="video-title-<%= video.id %>" class="title"><%= video.title %></p>
    <% end %>
    <% if video_users.present? %>
      <p>高評価しているユーザー</p>
      <% video_users.each do |user| %>
        <%= link_to videos_user_path(user) do %>
        <%= image_tag(user.avatar_url, class: "img-circle", size: '20x20') %>
        <span id="user-name-<%= user.id %>" class="user-name"><%= user.name %></span>
        <% end %>
      <% end %>
    <% end %>
    <p class="video-category"><%= "ジャンル：#{video.category.title_i18n}" %></p>
    <%= link_to users_channel_path(video.channel) do %>
      <p><%= "チャンネル名：#{video.channel.name}" %></p>
    <% end %>
    <%= link_to "動画のレビューを投稿する", new_content_path(video_url: video.video_id), class: "btn btn-primary" if logged_in? && current_user.videos.include?(video) %>
  </div>
</div>

app/views/videos/index.html.erb
<% content_for(:title, t(".title")) %>
<h1 class="page-title"><%= t(".title") %></h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="search-form">
      <div class="row">
        <p>『高評価動画の検索』</p>
        <%= form_with model: @search_videos_form, scope: :q, url: videos_path, method: :get do |f| %>
          <div class="col-md-4 col-md-offset-1 form-group">
            <%= f.label :channel_name, "チャンネル名" %>
            <%= f.search_field :channel_name, class: "form-control" %>
          </div>

          <div class="col-md-4 col-md-offset-2 form-group">
            <%= f.label :description, "内容" %>
            <%= f.search_field :description, class: "form-control" %>
          </div>

          <div class="col-md-4 col-md-offset-1 form-group">
            <%= f.label :category_title, "興味のあるジャンル" %>
            <%= f.select :category_title, Category.titles_i18n.invert.to_a, { include_blank: "興味のあるジャンル" }, class: "form-control" %>
          </div>

          <div class="col-md-4 col-md-offset-2 form-group">
            <%= f.label :users_generation, "登録ユーザの年齢" %>
            <%= f.select :users_generation, options_for_select(generations_hash, selected: @search_videos_form.users_generation), { include_blank: "年齢" }, class: "form-control" %>
          </div>

          <% if logged_in? %>
            <div class="col-md-6 col-md-offset-3 form-group">
              <%= f.hidden_field :follow_users, value: false, id: nil %>
              <%= f.hidden_field :following_user_ids, value: current_user.following_ids.join(','), id: nil %>
              <%= f.check_box :follow_users, { checked: @search_videos_form.follow_users }, true, false %>
              <%= f.label :follow_users, "フォローユーザーが高評価している動画のみ表示", class: "form-label" %>
            </div>
          <% end %>

          <div class="col-md-6 col-md-offset-3">
            <div class="row">
              <div class="col-md-5"><button type="button" id="clear-btn" class="btn btn-defalult btn-block">クリア</button></div>
              <div class="col-md-5"><%= f.submit "検索", class: "btn btn-primary btn-block" %></div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <% if @videos.length > 0 %>
      <span class="text-center"><%= paginate @videos, theme: 'bootstrap-5' %></span>
      <%= render @videos %>
      <span class="text-center"><%= paginate @videos, theme: 'bootstrap-5' %></span>
    <% else %>
      <p class="not-found">検索結果が存在しません</p>
    <% end %>
  </div>
</div>

app/views/videos/show.html.erb
<% content_for(:title, @video.title) %>

<div class="row">
  <div class="col-md-10 col-md-offset-1 video-show">

    <h1 id="video-title-<%= @video.id %>" class="video-title"><%= @video.title %></h1>

    <div class="video-detail">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe src=<%= "https://www.youtube.com/embed/#{@video.video_id}" %> class="embed-responsive-item" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      </div>
    </div>

    <div class="video-description">
      <h2>動画の概要説明</h2>
      <p><%= @video.description %></p>
    </div>

    <div class="video-link">
      <ul class="nav nav-tabs nav-justified">
        <li role="presentation" id="video-comment-link" class=<%= "active" if @link == 'comment' %>><%= link_to "コメント一覧", video_path(@video) %></li>
        <li role="presentation" id="video-user-link" class=<%= "active" if @link == 'user' %>><%= link_to "高評価しているユーザー一覧", video_path(@video, link: 'user') %></li>
      </ul>
    </div>

    <div class="video-contents">
      <%= render 'video_comments/video_comments' if @link == 'comment' %>
      <%= render 'users/video_users' if @link == 'user' %>
    </div>
  </div>
</div>