config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  root "static_pages#top"
  get "/privacypolicy", to: "static_pages#privacypolicy"
  get "/terms", to: "static_pages#terms"
  get "/login", to: "user_sessions#new"
  post "/login", to: "user_sessions#create"
  delete "/logout", to: "user_sessions#destroy"
  
  get 'auth/:provider/callback', to: "user_sessions#create"
  get 'auth/failure', to: redirect('/')

  resources :users do
    member do
      get :edit_best, :channels, :videos, :playlists, :contents, :following, :follower
    end
  end

  # 本番環境でメールサーバーの契約予定がないため削除
  # resources :password_resets, only: %i[new create edit update]
  
  resources :relationships, only: %i[create destroy]
  resources :channels, only: %i[index], shallow: true do
    resources :channel_comments, only: %i[new create edit update destroy]
    member do
      get :users, :videos, :comments, :playlists
    end
  end
  resources :videos, only: %i[index show], shallow: true do
    resources :video_comments, only: %i[new create edit update destroy]
  end
  resources :contents, shallow: true do
    resources :content_comments, only: %i[new create edit update destroy]
  end
  resources :content_favorites, only: %i[create destroy]
  resources :best_channels_favorites, only: %i[create destroy]
  resources :best_videos_favorites, only: %i[create destroy]
  resource :best_videos, only: %i[edit update]
  resource :best_channels, only: %i[edit update]
  resource :subscription_channels, only: %i[edit update]
  resource :popular_videos, only: %i[edit update]
  resource :recent_content, only: %i[show]
  resource :user_playlists, only: %i[edit update]
end

app/views/shared/_after_login_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="pull-left">
      <%= link_to "ユーザーチューブ", videos_path, class: "navbar-brand" %>
    </div>
    <div class="pull-right">
      <ul class="nav navbar-nav">
        <li id="dropdown" class="dropdown">
          <%= link_to current_user.name, '#', id: "account-name" %>
          <ul id="dropdown-menu" class="dropdown-menu">
            <li><%= link_to "マイページ", videos_user_path(current_user) %></li>
            <li><%= link_to "ユーザーの編集", edit_user_path(current_user) unless guest_user? %></li>
            <li><%= link_to "投稿の新規作成", new_content_path %></li>
            <li class="divider"></li>
            <li><%= link_to "ログアウト", logout_path, data: { turbo_method: :delete } %></li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class="pull-left">
          <%= link_to "ユーザーチューブ", root_path, class: "navbar-brand" %>
        </div>
        <div class="pull-right">
          <button type="button" id="hamburger" class="navbar-toggle collapsed">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
      </div>  
      <div class="collapse navbar-collapse" id="navbar-menu">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "ログイン", login_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_check_public.html.erb
<div class="text-center all-check-box">
  <%= label_tag "is_public" do %>
    <%= check_box_tag "is_public" %>
    <span><%= "すべての#{contents}を公開設定にする" %></span>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% unless %w[user_params user_name google_login].any?(message_type) %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-3 footer-item">
          <div>
            <p>お気に入りの動画を共有しよう。</p>
            <p class="footer-title">ユーザーチューブ</p>
          </div>
        </div>
        <div class="col-md-3 col-xs-6">
          <p>このサイトについて</p>
          <ul class="nav nav nav-pills nav-stacked">
            <li><%= link_to "- トップページ", root_path %></li>
            <li><%= link_to "- 利用規約", terms_path %></li>
            <li><%= link_to "- プライバシーポリシー", privacypolicy_path %></li>
          </ul>
        </div>
        <div class="col-md-3 col-xs-6">
          <p>一覧ページ</p>
          <ul class="nav nav nav-pills nav-stacked">
            <li><%= link_to "- 高評価動画一覧", videos_path %></li>
            <li><%= link_to "- チャンネル一覧", channels_path %></li>
            <li><%= link_to "- 投稿一覧", contents_path %></li>
            <li><%= link_to "- 新着コンテンツ一覧", recent_content_path %></li>
            <li><%= link_to "- ユーザー一覧", users_path %></li>
          </ul>
        </div>
        <div class="col-md-3 pc">
          <p>製作者について(外部サイト)</p>
          <ul class="nav nav nav-pills nav-stacked">
            <li><%= link_to "- GitHub", '#' %></li>
            <li><%= link_to "- Qiita", '#' %></li>
            <li><%= link_to "- wantedly", '#' %></li>
          </ul>
        </div>
        <div class='copyright'>
          <p>Copyright © 2023. nao All Rights reserved.</p>
        </div>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_google_analytics.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-N6YBE0HVWG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-N6YBE0HVWG');
</script>

app/views/shared/_google_login_btn.html.erb
<div class="google-login-btn">
  <%= form_with url: "/auth/google_oauth2", method: :post do %>
    <%= button_tag(type: :submit, data: { turbo: false }, class: 'gsi-material-button') do %>
      <div class="gsi-material-button-state"></div>
      <div class="gsi-material-button-content-wrapper">
        <div class="gsi-material-button-icon">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: block;">
            <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
            <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
            <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
            <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
            <path fill="none" d="M0 0h48v48H0z"></path>
          </svg>
        </div>
        <span class="gsi-material-button-contents">Googleでログイン</span>
        <span style="display: none;">Googleでログイン</span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_header.html.erb
<% if logged_in? %>
  <%= render 'shared/after_login_header' %>
<% else %>
  <%= render 'shared/before_login_header' %>
<% end %>

<div class="smart-phone">
  <div class="site-link">
    <div><%= link_to "高評価動画一覧", videos_path, class: "#{"active" if current_page?(videos_path)}" %></div>
    <div><%= link_to "チャンネル一覧", channels_path, class: "#{"active" if current_page?(channels_path)}" %></div>
    <div><%= link_to "投稿一覧", contents_path, class: "#{"active" if current_page?(contents_path)}" %></div>
    <div><%= link_to "新着コンテンツ一覧", recent_content_path, class: "#{"active" if current_page?(recent_content_path)}" %></div> 
    <div><%= link_to "ユーザー一覧", users_path, class: "#{"active" if current_page?(users_path)}" %></div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="pc">
  <div class="sidebar text-center">
    <nav class="navbar navbar-default">
      <ul class="nav nav-pills nav-stacked">
        <li role="presentation"><%= link_to "高評価動画一覧", videos_path %></li>
        <li role="presentation"><%= link_to "チャンネル一覧", channels_path %></li>
        <li role="presentation"><%= link_to "投稿一覧", contents_path %></li>
        <li role="presentation"><%= link_to "新着コンテンツ一覧", recent_content_path %></li>
        <li role="presentation"><%= link_to "ユーザー一覧", users_path %></li>
      </ul>
    </nav>
  </div>
</div>