config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  root "static_pages#top"
  get "/privacypolicy", to: "static_pages#privacypolicy"
  get "/terms", to: "static_pages#terms"
  get "/login", to: "user_sessions#new"
  post "/login", to: "user_sessions#create"
  delete "/logout", to: "user_sessions#destroy"
  
  get 'auth/:provider/callback', to: "user_sessions#create"
  get 'auth/failure', to: redirect('/')

  resources :users do
    member do
      get :edit_best, :channels, :videos, :playlists, :contents, :following, :follower
    end
  end

  # 本番環境でメールサーバーの契約予定がないため削除
  # resources :password_resets, only: %i[new create edit update]
  
  resources :relationships, only: %i[create destroy]
  resources :channels, only: %i[index], shallow: true do
    resources :channel_comments, only: %i[new create edit update destroy]
    member do
      get :users, :videos, :comments, :playlists
    end
  end
  resources :videos, only: %i[index show], shallow: true do
    resources :video_comments, only: %i[new create edit update destroy]
  end
  resources :contents, shallow: true do
    resources :content_comments, only: %i[new create edit update destroy]
  end
  resources :content_favorites, only: %i[create destroy]
  resources :best_channels_favorites, only: %i[create destroy]
  resources :best_videos_favorites, only: %i[create destroy]
  resource :best_videos, only: %i[edit update]
  resource :best_channels, only: %i[edit update]
  resource :subscription_channels, only: %i[edit update]
  resource :popular_videos, only: %i[edit update]
  resource :recent_content, only: %i[show]
  resource :user_playlists, only: %i[edit update]
end

app/models/channel_comment.rb
class ChannelComment < ApplicationRecord
  belongs_to :user
  belongs_to :channel

  validates :body, presence: true, length: { maximum: 400 }

  default_scope -> { order(created_at: :desc) }
end

app/controllers/channel_comments_controller.rb
class ChannelCommentsController < ApplicationController
  before_action :set_channel, only: %i[new create]
  before_action :set_channel_comment, only: %i[edit update destroy]

  def new
    @channel_comment = current_user.channel_comments.build
  end

  def create
    @channel_comment = current_user.channel_comments.build(channel_comment_params)

    if @channel_comment.save
      redirect_to comments_channel_url(@channel), success: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @channel_comment.update(channel_comment_params)
      redirect_to @channel_comment.channel, success: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @channel = @channel_comment.channel
    @channel_comments = @channel.channel_comments.includes(:user).page(params[:page])
    @channel_comment.destroy!
    respond_to do |format|
      format.html { redirect_to @channel, success: t('.success'), status: :see_other }
      format.turbo_stream { flash.now[:success] = t('.success') }
    end
  end

  private

  def channel_comment_params
    params.require(:channel_comment).permit(:body, :channel_id)
  end

  def set_channel
    @channel = Channel.find(params[:channel_id])
  end

  def set_channel_comment
    @channel_comment = current_user.channel_comments.find(params[:id])
  end
end

app/views/channel_comments/_channel_comment.html.erb
<div class="channel-comment">
  <div class="user-info">
    <%= link_to channels_user_path(channel_comment.user) do %>
      <%= image_tag(channel_comment.user.avatar_url, class: "img-circle", size: '50x50') %>
      <span id="user-name-<%= channel_comment.user.id %>" class="user-name"><%= channel_comment.user.name %></span>
    <% end %>
  </div>
  <pre id="comment-body-<%= channel_comment.id %>"><%= channel_comment.body %></pre>
  <% if current_user?(channel_comment.user) %>
    <%= link_to "編集", edit_channel_comment_path(channel_comment), class: "btn btn-primary" %>
    <%= link_to "削除", channel_comment, data: { "turbo-method": :delete, turbo_confirm: "コメントを削除してよろしいですか?" }, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/channel_comments/_channel_comments.html.erb
<div id="channel-comments" class="channel-comments">
  <div>
    <%= link_to "コメントの新規作成", new_channel_channel_comment_path(@channel), class: "btn btn-primary btn-block" if logged_in? %>
  </div>
  <div>
    <div class="text-center"><%= paginate @channel_comments, theme: 'bootstrap-5' %></div>
    <%= render @channel_comments %>
    <div class="text-center"><%= paginate @channel_comments, theme: 'bootstrap-5' %></div>
  </div>
</div>

app/views/channel_comments/destroy.turbo_stream.erb
<%= turbo_stream.update "channel-comments" do %>
  <div class="mt-30">
    <%= link_to "コメントの新規作成", new_channel_channel_comment_path(@channel), class: "btn btn-primary btn-block" %>
  </div>
  <div class="text-center"><%= paginate @channel_comments, theme: 'bootstrap-5' %></div>
  <%= render @channel_comments %>
  <div class="text-center"><%= paginate @channel_comments, theme: 'bootstrap-5' %></div>
<% end %>

<%= turbo_stream.update "flash-message" do %>
  <%= render 'shared/flash_message' %>
<% end %>

app/views/channel_comments/edit.html.erb
<% content_for(:title, t(".title")) %>
<h1 class="text-center"><%= t(".title") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @channel_comment do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group mt-30">
        <%= f.text_area :body, size: "40x10", class: "form-control" %>
      </div>

      <%= f.submit "投稿する", class: "btn btn-primary btn-block mt-30" %>
    <% end %>
  </div>
</div>

app/views/channel_comments/new.html.erb
<% content_for(:title, t(".title")) %>
<h1 class="text-center"><%= t(".title") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @channel_comment, url: channel_channel_comments_path(@channel) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.hidden_field :channel_id, value: @channel.id %>

      <div class="form-group mt-30">
        <%= f.text_area :body, size: "40x10", class: "form-control" %>
      </div>

      <%= f.submit "投稿する", class: "btn btn-primary btn-block mt-30" %>
    <% end %>
  </div>
</div>